apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway

spec: 
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100M"
              cpu: "100m"
            limits:
              memory: "250M"
              cpu: "200m"
          image: fairwayfriends.azurecr.io/gateway:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: gateway-configmap
            - secretRef:
                name: gateway-secret