apiVersion: apps/v1
kind: Deployment
metadata:
  name: postservice
  labels:
    app: postservice

spec: 
  replicas: 2
  selector:
    matchLabels:
      app: postservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: postservice
    spec:
      containers:
        - name: postservice
          image: whstrauch/postservice
          ports:
            - containerPort: 5003
          envFrom:
            - configMapRef:
                name: postservice-configmap
            - secretRef:
                name: postservice-secret