apiVersion: v1
kind: ConfigMap
metadata:
  name: courseservice-configmap
data:
  POSTGRESQL_HOST: fairway-friends.postgres.database.azure.com
  POSTGRESQL_USER: whstrauch
  POSTGRESQL_DB: golfcourses
  POSTGRESQL_PORT: "5432"