apiVersion: apps/v1
kind: Deployment
metadata:
  name: courseservice
  labels:
    app: courseservice

spec: 
  replicas: 1
  selector:
    matchLabels:
      app: courseservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: courseservice
    spec:
      containers:
        - name: courseservice
          image: fairwayfriends.azurecr.io/courseservice
          ports:
            - containerPort: 5005
          envFrom:
            - configMapRef:
                name: courseservice-configmap
            - secretRef:
                name: courseservice-secret