apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  labels:
    app: authservice

spec: 
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: fairwayfriends.azurecr.io/authservice
          resources:
            requests:
              memory: "100M"
              cpu: "100m"
            limits:
              memory: "250M"
              cpu: "200m"
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: authservice-configmap
            - secretRef:
                name: authservice-secret