[project]
name = "authservice"
version = "1.0.0"
description = "Authentication service for fairwayfriends."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core>=3.4"]
build-backend = "flit_core.buildapi"