apiVersion: v1
kind: ConfigMap
metadata:
  name: scoreservice-configmap
data:
  MONGODB_HOST: fairway-friends.mongo.cosmos.azure.com
  MONGODB_USER: fairway-friends
  MONGODB_CONNECTION_STRING: mongodb://fairway-friends:9mbrZ5xFLABbcPUbEhw6LWEa8LGrm616jViVicnFxXsSvHljWbUxKhKeeviDb1cqviJGsSKTOCZmACDbCHck5g==@fairway-friends.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@fairway-friends@
  MONGODB_DB: scores
  MONGODB_PORT: "10255"